### ISSUE TITLE
Move IV.H (Measurement Approaches) to related work

### ISSUE THREAD

**Issue by cschwartz** [mas-ude/onlinegame-lag-sim#3]
Can we move the Measurement Approaches subsection to related work, while re-using Fig. 9 for the end2end latency section?
Opinions?

**Comment by fmetzger** [comment]
Sounds fine to me. But before talking about measurement approaches for games (and in particular the e2e lag) should we not first discuss/present the e2e lag itself?
So maybe a background / basic mechanics section and only afterwards the related work?

**Comment by cschwartz** [comment]
Sounds reasonable. Care to change the order yourself?

**Comment by fmetzger** [comment]
Done some first steps in that direction. Not really happy about it yet, but I'll leave it as-is for now.

**Comment by fmetzger** [comment]
This issue should outdated with the submitted version.
